config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/show'
  get 'posts/edit'
  resources :videos
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :posts
  devise_for :users
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :tweets
  root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :posts
end

app/models/video.rb
class Video < ApplicationRecord
    has_one_attached :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
  
  end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
      redirect_to  user_path(current_user.id)
    else
      redirect_to :action => "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:body, :youtube_url)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end
    
    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
    end

      private
      def tweet_params
        params.require(:tweet).permit(:body, :youtube_url)
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def find_youtube_url(youtube_url)
        if youtube_url.include?("https://youtu.be/")
          youtube_url.strip.gsub("https://youtu.be/", "")
          # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        else
          youtube_url.strip.gsub("https://www.youtube.com/watch?v=", "")
          # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        end
      end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.
<div class="logo-image"=>
    <%= link_to hello_index_path do %>
    <%= image_tag 'image1.png' ,size: '200×200' %>
    <% end %>
</div>

    <%= link_to '投稿一覧へ', tweets_index_path =%>
        
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url, :size => 140 %><br>
    <%= f.label :body %><br>
    <%= f.text_field :body, :size => 140 %> <br>
    <%= f.submit "投稿する" %>
  <% end %>

app/views/posts/index.html.haml
%h1 Posts#index
%p Find me in app/views/posts/index.html.haml

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url, :size => 140 %><br>
    <%= f.label :body %><br>
    <%= f.text_field :body, :size => 140 %> <br>
    <%= f.submit "投稿する" %>
  <% end %>

app/views/posts/show.html.haml
%h1 Posts#show
%p Find me in app/views/posts/show.html.haml

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>
  

app/views/tweets/index.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet一覧</h3>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.body %>
      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= t.user.email %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_index_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
</div>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>
<%= link_to "Tweet一覧に戻る", tweets_index_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<%= link_to "お気に入り動画投稿", posts_new_path %>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<h2>お気に入り動画</h2>
<% @user.posts.each do |t| %>
    <% if t.youtube_url.present? %>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
    <%= t.body %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <%= link_to "編集する", edit_post_path(t.id) %>
    <%= button_to "削除する", post_path(t.id), method: :delete %>
  <% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>